{
 "title": "Vagrant Minecraft Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JMX Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"Metaspace\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"Compressed Class Space\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"Code Cache\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"PS Old Gen\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"PS Survivor Space\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"PS Eden Space\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Load1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_load1{instance=\"localhost:9100\",job=\"node_exporter\"}[5m])"
    }
   ]
  },
  {
   "title": "Memory free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes" },
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  }
 ]
}